[package]
name = "docker-image-pusher"
version = "0.3.0"
edition = "2024"
authors = ["yorelog <yorelog@gmail.com>"]
description = "High-performance command-line tool for pushing Docker image tar packages directly to Docker registries"
license = "MIT"
repository = "https://github.com/yorelog/docker-image-pusher"
homepage = "https://github.com/yorelog/docker-image-pusher"
documentation = "https://docs.rs/docker-image-pusher"
readme = "README.md"
keywords = ["docker", "registry", "push", "container", "tar"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
reqwest = { version = "0.12.19", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22.1"
sha2 = "0.10"
hex = "0.4"
clap = { version = "4.5", features = ["derive"] }
tar = "0.4"
flate2 = "1.1.2"
thiserror = "2.0.12"
futures = "0.3"
async-trait = "0.1"
url = "2.5"
futures-util = "0.3"
uuid = "1.17.0"
oci-client = "0.15.0"


[[example]]
name = "comprehensive_demo"
path = "examples/comprehensive_demo.rs"

[[example]]
name = "optimized_upload_demo"
path = "examples/optimized_upload_demo.rs"

[[example]]
name = "oci_client_integration_demo"
path = "examples/oci_client_integration_demo.rs"




