[package]
name = "docker-image-pusher"
version = "0.1.1"
edition = "2021"
description = "A command-line tool for pushing Docker image tar packages directly to Docker registries with chunked upload support"
license = "MIT"
authors = ["yorelog <yorelog@gmail.com>"]
repository = "https://github.com/yorelog/docker-image-pusher"
homepage = "https://github.com/yorelog/docker-image-pusher"
documentation = "https://github.com/yorelog/docker-image-pusher"
keywords = ["docker", "docker-registry-v2", "docker-tar", "upload", "cli"]
categories = ["command-line-utilities", "development-tools"]
readme = "README.md"

[dependencies]
reqwest = { version = "0.12", features = ["json", "stream"] }
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
sha2 = "0.10"
clap = { version = "4.4", features = ["derive"] }
url = "2.4"
anyhow = "1.0.98"
base64 = "0.22.1"
