[package]
name = "docker-image-pusher"
version = "0.2.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.19", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22.1"
sha2 = "0.10"
hex = "0.4"
clap = { version = "4.5", features = ["derive"] }
tar = "0.4"
flate2 = "1.1.2"
thiserror = "2.0.12"
futures = "0.3"
async-trait = "0.1"
url = "2.5"
futures-util = "0.3"

# Examples showcasing the 4 core operation modes
[[example]]
name = "pull_and_cache_demo"
path = "examples/pull_and_cache_demo.rs"

[[example]]
name = "extract_and_cache_demo"
path = "examples/extract_and_cache_demo.rs"

[[example]]
name = "push_from_cache_manifest_demo"
path = "examples/push_from_cache_manifest_demo.rs"

[[example]]
name = "push_from_cache_tar_demo"
path = "examples/push_from_cache_tar_demo.rs"

[[example]]
name = "comprehensive_demo"
path = "examples/comprehensive_demo.rs"

[[example]]
name = "optimized_upload_demo"
path = "examples/optimized_upload_demo.rs"

[[example]]
name = "auth_test_demo"
path = "examples/auth_test_demo.rs"

[[example]]
name = "large_image_test_demo"
path = "examples/large_image_test_demo.rs"

[[example]]
name = "push_to_aliyun_demo"
path = "examples/push_to_aliyun_demo.rs"


